misc:
  messages:
    reload: "&a[*] LivecraftBungeeEssentials reloaded"
    no-permission: "&c[*] You don't have permission to use this command"
    unknown-command: "&c[*] Unknown command"
    player-only: "&c[*] Sorry, players only"
    unknown-player: "&c[*] Could not find {1}"
    back: "&6Returning to previous location"
    back-error: "&cCould not find previous location"
#
modules:
  #
  emote:
    enable: true
    commands:
      enabled: true
      # Commands that can be parsed for emotes
      whitelisted-commands:
        - "/msg"
        - "/r"
        - "/a"
        - "/pc"
        - "/emsg"
        - "/er"
        - "/me"
        - "/nick"
        - "/enick"
        - "/say"
        - "/bc"
    emotes:
      hugs: "༼つ◕_◕༽つ"
      shrug: "¯\\_(ツ)_/¯"
      tableflip: "(╯°□°）╯︵ ┻━┻"
      bear: "(ᵔᴥᵔ)"
      teddy: "ʕ•ᴥ•ʔ"
      glasses: "ಠ⌣ಠ"
      frown: "^︵^"
      lenny: "(͡ʖ͡)"
      owo: "(｡◕‿‿◕｡)"
      why: "ლ(ಠ益ಠლ)"
      aww: "(◕‿◕✿)"
      zoidberg: "(/) (°,,°) (/)"
      heart: "\u2764"
      goldstar: "\u272A"
      star: "\u2b50"
      tm: "\u2122"
      check: "\u2714"
      ex: "\u2716"
      music: "♪♫♫♪"
      copyright: "\u00A9"
      rain: "\u2601"
      thunder: "\u2608"
      sun: "\u2600"
      moon: "\u263d"
      snowman: "\u2603"
      snowflake: "\u2744"
      peace: "\u262E"
      flower: "\u273F"
      rose: "\u2698"
      happy: "\u263B"
      sad: "\u2639"
      pencil: "\u270E"
      udq: "¿"
      rip: "\u2620"
      swords: "\u2694"
      square: "\u29c8"
      infinity: "\u221e"
      darrow: "»"
      nuke: "\u2622"
      omega: "\u03A9"
      spade: "\u2660"
      club: "\u2663"
      diamond: "\u2666"
      communism: "\u262D"
      coffee: "\u2615"
      caution: "\u26A0"
      zap: "\u26A1"
      treasure: "\u2718"
      note: "\u266C"
      uwu: "☜ NO"
      chile: "\u2766"
      coin: "\u23FC"
      coin1: "\u26C0"
      coins1: "\u26C1"
      coin2: "\u26C2"
      coins2: "\u26C3"
      acorn: "\u26E8"
      flag: "\u2691"
      pick: "\u26cf"
      fire: "\u2632"
      anchor: "\u2693"
      left: "\u2190"
      up: "\u2191"
      right: "\u2192"
      down: "\u2193"
      pleft: "\u23F4"
      pup: "\u23F6"
      pright: "\u23F5"
      pdown: "\u23F7"
      power: "\u23FB"
      lamda: "\u03bb"
      male: "\u2642"
      female: "\u2640"
      hry: "\u20B4"
      euro: "\u20AC"
      bullet: "\u2022"
      dice1: "\u2680"
      dice2: "\u2681"
      dice3: "\u2682"
      dice4: "\u2683"
      dice5: "\u2684"
      dice6: "\u2685"
      1: "\u2460"
      2: "\u2461"
      3: "\u2462"
      4: "\u2463"
      5: "\u2464"
      6: "\u2465"
      7: "\u2466"
      8: "\u2467"
      9: "\u2468"
      10: "\u2469"
      n1: "\u278A"
      n2: "\u278B"
      n3: "\u278C"
      n4: "\u278D"
      n5: "\u278E"
      n6: "\u278F"
      n7: "\u2790"
      n8: "\u2791"
      n9: "\u2792"
      n10: "\u2793"
      0: "\u24EA"
      a: "\u24B6"
      b: "\u24B7"
      c: "\u24B8"
      d: "\u24B9"
      e: "\u24BA"
      f: "\u24BB"
      g: "\u24BC"
      h: "\u24BD"
      i: "\u24BE"
      j: "\u24BF"
      k: "\u24C0"
      l: "\u24C1"
      m: "\u24C2"
      n: "\u24C3"
      o: "\u24C4"
      p: "\u24C5"
      q: "\u24C6"
      r: "\u24C7"
      s: "\u24C8"
      t: "\u24C9"
      u: "\u24CA"
      v: "\u24CB"
      w: "\u24CC"
      x: "\u24CD"
      y: "\u24CE"
      z: "\u24CF"
      test: "\u0296"
      black: "\u00A70"
      darkblue: "\u00A71"
      darkgreen: "\u00A72"
      darkaqua: "\u00A73"
      darkred: "\u00A74"
      darkpurple: "\u00A75"
      gold: "\u00A76"
      gray: "\u00A77"
      darkgray: "\u00A78"
      blue: "\u00A79"
      green: "\u00A7a"
      aqua: "\u00A7b"
      red: "\u00A7c"
      lightpurple: "\u00A7d"
      yellow: "\u00A7e"
      white: "\u00A7f"
      magic: "\u00A7k"
      bold: "\u00A7l"
      strike: "\u00A7m"
      underline: "\u00A7n"
      italic: "\u00A7o"
      reset: "\u00A7r"
  #
  homes:
    enabled: true
    messages:
      set: "&a[*] Home was set. Use &7/home &ato return to this spot"
      set-multiple: "&a[*] Home '&7{1}&a' was set. Use &7/home {1} &ato return to this spot"
      set-multiple-permission: "&c[*] You don't have permission to set multiple homes"
      bed-set: "&a[*] Bed spawn set!"
      delete: "&a[*] Home &7'{1}&a' was deleted"
      delete-error: "&c[*] '&f{1}&c' does not exist"
      missing: "&c[*] Hmm, that home appears to be missing"
      reserved: "&c[*] {1} cannot be set manually"
      limit-reached: "&c[*] You cannot set more than &6{1} &chomes."
      home-set-usage: "&c[*] Usage: &7/sethome <name>"
      home-set-error: "&c[*] There was an error setting this home, please try again"
      # {1}: How many homes the player currently has
      # {2}: How many homes the player can have
      # {3}: All homes the player has separated by ','
      list:
        - "&a[*] Homes (&e{1}&a/&e{2}&a)"
        - "&f{3}"
      # {1} How many homes the player currently has
      # {2}: All homes the player has separated by ','
      list-unlimited:
        - "&a[*] Homes (&e{1}&a/&eUnlimited&a)"
        - "&f{2}"
  #
  markdown:
    enabled: true
    # Apply markdown to commands
    commands:
      enabled: true
      # Commands that can be parsed for markdown
      whitelisted-commands:
        - "/msg"
        - "/r"
        - "/a"
        - "/pc"
        - "/emsg"
        - "/er"
        - "/me"
        - "/nick"
        - "/enick"
        - "/say"
    formats:
      bold-italic:
        regex: "\\*{3}(.*?)\\*{3}"
        replacement: "&l&o{1}&r"
        priority: 1
      bold:
        regex: "\\*{2}(.*?)\\*{2}"
        replacement: "&l{1}&r"
        priority: 5
      italic:
        regex: "\\*(.*?)\\*"
        replacement: "&o{1}&r"
        priority: 10
      underline:
        regex: "__(.*?)__"
        replacement: "&n{1}&r"
        priority: 15
      italic-alternate:
        regex: "\\b_(.*?)_\\b"
        replacement: "&o{1}&r"
        priority: 20
      strikethrough:
        regex: "~~(.*?)~~"
        replacement: "&m{1}&r"
        priority: 25
  #
  motd:
    enabled: true
    maintenance:
      # Enable maintenance mode.
      # Will display a different motd on the server list
      # and kick anyone trying to join
      enabled: false
      motd: "&5❤ &aLivecraft: Online Since 2011 &5❤/n&4Maintenance mode. We'll be back shortly!"
      kick-message: "&cLivecraft is in maintenance mode. We'll be back shortly"
      whitelist:
        - Medius_Echo
        - alfonsojon
        - SentinelLion
    line-width: 250
    fallback-motd: "&5❤ &aLivecraft: Online Since 2011 &5❤/n&8- &71.15.2 &8-"
    motds:
      - "&5❤ &71.15.2 - &aLivecraft: Online Since 2011 &5❤/n&fWelcome back &3%player%&f!"
  #
  ping:
    enabled: true
    player-highlight: "&3{1}&r"
    include-nicknames: true
    special-pings:
      random:
        enabled: true
        highlight: "&5{1}&r"
        aliases:
          - someone
          - anyone
    groups:
      enabled: true
      groups:
        staff:
          highlight: "&c{1}&r"
          aliases:
            - staff
        admin:
          highlight: "&c{1}&r"
          aliases:
            - admin
            - administrator
        global:
          highlight: "&c{1}&r"
          aliases:
            - everyone
            - here
    commands:
      enabled: true
      whitelist:
        - "/say"
        - "/bc"
        - "/a"
  #
  teleport:
    enabled: true
    # How long a pending teleport request will wait before
    # timing out.
    timeout: 120
    messages:
      # Misc
      error: "&c[*] There was an error teleporting, please try again"
      pending-error: "&c[*] You don't have any pending teleport requests"
      # Teleport Requests
      request-sent:
        - "&6Request sent to &c{1}"
        - "&6To cancel this request, type &c/tpacancel"
      request-tip:
        - "&6To teleport, type &c/tpaccept"
        - "&6To deny this request, type &c/tpdeny"
        - "&6This request will timeout after &c{1} seconds&6."
      request-accepted: "&6Teleport request accepted"
      request-accepted-from: "&6{1} &caccepted your teleport request."
      request-denied: "&6Teleport request denied."
      request-denied-from: "&c{1} &6denied your teleport request."
      request-cancel: "&6Pending teleport request cancelled."
      request-cancel-from: "&c{1} &6cancelled their request."
      request-cancel-tip: "&6To cancel this request, type &c/tpacancel"
      request-self: "&cYou can't teleport to yourself"
      request-timed-out: "&4Teleport request has timed out."
      # Teleport commands
      tpa: "&c{1} &6has requested to teleport to you."
      teleport-usage: "&c[*] Missing player name"
      tpahere: "&c{1} &6has requested that you teleport to them."
      teleporting: "&6Teleporting..."
      teleporting-to-player: "&6Teleporting to &c{1}&6."
  warps:
    enabled: true
    messages:
      set: "&a[*] Warp was set. Use &7/warp {1} &ato warp to this spot"
      delete: "&c[*] Warp '&7{1}&c' was deleted"
      missing: "&c[*] Hmm, that warp appears to be missing"
      teleporting: "&a[*] Warping to &7{1}"
      teleport-permission: "&c[*] You don't have permission to use that warp"
